export const ACCOUNT = '/account'
export const ADMIN = '/admin'
export const HOME = '/home'
export const LANDING = '/'
export const PASSWORD_FORGET = '/pw-forget'
export const SIGN_IN = '/signin'
export const SIGN_UP = '/signup'
